version: "3.9"
services:
  php-fpm:
    build: ./php-fpm
    volumes: 
      - public:/var/www/html/public
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - public:/var/www/html/public
volumes: 
  public: