version: "3.9"
services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - public:/var/www/html/public
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - public:/var/www/html/public
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: first_database
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
volumes:
  public: